-
  name: Automate application deployment
  hosts: centos
  vars:
    packages:
      - firewalld
      - httpd
      - mariadb

  tasks:
      -
        package:
          name: "{{ item }}"
          state: present
        with_items: "{{ packages }}"

      - name: "Start packages"
        service:
          name: "{{ item }}"
          enabled: true
          state: started
        with_items: "{{ packages }}"

