-
  name: Automate application deployment
  hosts: centos
  vars:
    packages:
      - firewalld
      - httpd
      - mariadb

  tasks:
      -
        package:
          name: "{{ item }}"
          state: present
        with_items: "{{ packages }}"



