-
  name: "Run script conditionally"
  hosts: all_servers
  gather_facts: true
  tasks:

    - name: "Install firewalld for Redhat and Debian"
      package:
        name: firewalld
        state: present
      when: ansible_os_family == "RedHat"

    - name: "Enable firewalld for Redhat and Debian"
      service:
        name: firewalld
        state: started
      when: ansible_os_family == "RedHat"

    - name: "Read /etc/resolv.conf"
      shell: 'cat /etc/resolv.conf'
      register: command_output

    - debug:
        var: command_output.stdout_lines

    - name: "Save command_output to a file"
      copy:
        content: "{{ command_output.stdout }}"
        dest: output.txt
      delegate_to: localhost

    - shell: echo "nameserver 1.1.1.1" >> /etc/resolv.conf
      when: command_output.stdout.find("1.1.1.1") == -1




