-
  name: "Execute a script on all centos nodes"
  hosts: centos
  tasks:
    - name: "Update entry into /etc/resolv.conf"
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 10.1.250.10"
    
    - name: "Add new group"
      group:
        name: developers
        state: present 
    - name: "Create a new user"
      user:
        name: subiaclarence
        uid: 1040
        group: developers


    - name: "Run the script"
      script: ~/ansible4beginners/demo/test_script.sh

    - name: "Start httpd service"
      service:
        name: httpd
        state: started

